version: '3.8'

services:
  app:
    image: node:24
    volumes:
      - ../..:/workspaces
      
    command: sleep infinity


  db:
    image: postgres:17-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

volumes:
  postgres-data: